#!/bin/sh

set -eu

ARCH=$(uname -m)

echo "Installing build dependencies..."
echo "---------------------------------------------------------------"
pacman -Syu --noconfirm \
	alsa-lib          \
	cmake             \
	elfutils          \
	glib2             \
	glib2-devel       \
	graphene          \
	gtk4              \
	gtk4-layer-shell  \
	jdk8-openjdk      \
	jre-openjdk       \
	libbsd            \
	libcap            \
	libglvnd          \
	libgudev          \
	libpng            \
	libportal         \
	libsndfile        \
	libunwind         \
	lz4               \
	meson             \
	openxr            \
	openssl           \
	pipewire-audio    \
	sdl2              \
	sqlite            \
	valgrind          \
	vulkan-headers    \
	vulkan-icd-loader \
	wayland-protocols \
	webkitgtk-6.0     \
	xz                \
	zlib              \
	zip

echo "Installing debloated packages..."
echo "---------------------------------------------------------------"
get-debloated-pkgs --add-common --prefer-nano ffmpeg-mini

# the build needs java 8 to compile the old java code, make sure it
# is the java/javac that gets used during the builds
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export PATH="$JAVA_HOME/bin:$PATH"
# some java tools run out of memory on low memory machines, especially
# dx when dexing the android core libraries, bump the default heap
export JAVA_TOOL_OPTIONS=-Xmx4096M

ATL_SOURCE=https://gitlab.com/android_translation_layer

build_meson_bin() (
	repo=$1
	shift

	echo "Building $ATL_SOURCE/$repo..."
	echo "---------------------------------------------------------------"
	git clone "$ATL_SOURCE/$repo" ./"$repo"
	cd ./"$repo"

	if [ "$repo" = 'android_translation_layer' ]; then
		# fix desktop entries generated by ATL
		patch -p1 < ../patches/atl-desktop-entry-binary-path.patch
		git rev-parse --short HEAD > ~/version
	fi

	meson setup build --prefix=/usr --libdir=lib --buildtype=release "$@"
	meson compile -C build
	meson install -C build
)

# wolfssl needs to be built with jni support enabled for art_standalone
build_wolfssl() (
	echo "Building wolfssl..."
	echo "---------------------------------------------------------------"
	curl -L -o wolfssl.tar.gz "https://github.com/wolfSSL/wolfssl/archive/refs/tags/v5.9.2-stable.tar.gz"
	tar -xzf wolfssl.tar.gz
	cd wolfssl-5.9.2-stable

	./autogen.sh

	./configure \
		--prefix=/usr                 \
		--libdir=/usr/lib             \
		--sysconfdir=/etc             \
		--mandir=/usr/share/man       \
		--localstatedir=/var          \
		--enable-shared               \
		--enable-static               \
		--enable-reproducible-build   \
		--disable-opensslall          \
		--disable-opensslextra        \
		--enable-aescbc-length-checks \
		--enable-curve25519           \
		--enable-ed25519              \
		--enable-ed25519-stream       \
		--disable-oldtls              \
		--enable-base64encode         \
		--enable-tlsx                 \
		--enable-scrypt               \
		--disable-examples            \
		--enable-keygen               \
		--enable-wolfssh              \
		--enable-jni

	make -j"$(nproc)"
	make install
)

# vixl is needed by art_standalone to build the aarch64 dex2oat code,
# on x86_64 it's not needed so we only build it there, see the atl aports
# recipe for how the aarch64 build provides it
build_vixl() (
	echo "Building vixl..."
	echo "---------------------------------------------------------------"
	curl -L -o vixl-7.0.0.tar.gz "https://github.com/Linaro/vixl/archive/refs/tags/7.0.0.tar.gz"
	tar -xzf vixl-7.0.0.tar.gz
	cd vixl-7.0.0

	patch -p1 < ../patches/vixl-meson-support.patch

	meson setup build --prefix=/usr --libdir=lib --buildtype=release -Dsimulator=none
	meson compile -C build
	meson install -C build
)

build_art_standalone() (
	echo "Building $ATL_SOURCE/art_standalone..."
	echo "---------------------------------------------------------------"
	git clone "$ATL_SOURCE/art_standalone" ./art_standalone
	cd ./art_standalone

	# make art resolve addr2line through PATH instead of the hardcoded /usr/bin/addr2line
	patch -p1 < ../patches/art-addr2line-path.patch
	# give dx more heap when dexing the core libraries
	patch -p1 < ../patches/art-dx-heap.patch
	# use the host's java cacerts instead of bundling a copy in the AppImage
	patch -p1 < ../patches/art-wolfssljni-host-cacerts.patch

	make ____PREFIX=/usr ____LIBDIR=lib -j"$(nproc)"
	make ____PREFIX=/usr ____INSTALL_ETC=/etc ____LIBDIR=lib install
)

# art_standalone requires wolfssl and bionic_translation
if [ "$ARCH" = 'aarch64' ]; then
	build_vixl
fi
build_wolfssl
build_meson_bin bionic_translation
build_art_standalone
build_meson_bin libopensles-standalone
build_meson_bin android_translation_layer

# java 8 is only needed to build, get rid of it so that the resulting
# AppImage does not bundle the wrong java runtime
pacman -Rns --noconfirm jdk8-openjdk


